#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef SHUFTIPRO_SWIFT_H
#define SHUFTIPRO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShuftiPro",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS("_TtC9ShuftiPro11InsetsLabel")
@interface InsetsLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro23AlertLabelManualCapture")
@interface AlertLabelManualCapture : InsetsLabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

/// Can be <code>UIView</code> or <code>UIBarButtonItem</code>.
SWIFT_PROTOCOL("_TtP9ShuftiPro10AnchorView_")
@protocol AnchorView
@property (nonatomic, readonly, strong) UIView * _Nonnull plainView;
@end


SWIFT_CLASS("_TtC9ShuftiPro18BracketsBorderView")
@interface BracketsBorderView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro7CallApi")
@interface CallApi : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC9ShuftiPro31CameraInstructionViewController")
@interface CameraInstructionViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified documentInstructions;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel4;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel5;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleForInstructions;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified crossImage;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified documentView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified commonInstructionView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified commonLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified commonLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified commonLabel3;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified commonImage1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified commonImage2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified commonImage3;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)crossButtonClickAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC9ShuftiPro17CustomAppDelegate")
@interface CustomAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (UIInterfaceOrientationMask)application:(UIApplication * _Nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
- (void)application:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)handleEventsForBackgroundURLSessionidentifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSLayoutConstraint;
@class UITapGestureRecognizer;
@class UISwipeGestureRecognizer;

SWIFT_CLASS("_TtC9ShuftiPro12CustomSwitch")
@interface CustomSwitch : UIView
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified switchMainView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified NALabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified circleView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified trailingCircleView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified topSpace;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)chnageSwitch:(UITapGestureRecognizer * _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
@end


SWIFT_CLASS("_TtC9ShuftiPro31DataLoadingScreenViewController")
@interface DataLoadingScreenViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loaderBackView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface DataLoadingScreenViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)presentGeneralAlertInternetIssue;
@end

@class UITableView;
@class WKWebView;
@class UITextView;
@class LoadingButton;

SWIFT_CLASS("_TtC9ShuftiPro27DeclineResultViewController")
@interface DeclineResultViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loaderView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified verificationText;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified termsAndConditionTextView;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified proceedButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)proceedButtonClickAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class NSURL;

@interface DeclineResultViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
@end

@class NSIndexPath;
@class UITableViewCell;

@interface DeclineResultViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@class UIColor;
@class UIFont;

/// A Material Design drop down in replacement for <code>UIPickerView</code>.
SWIFT_CLASS("_TtC9ShuftiPro8DropDown")
@interface DropDown : UIView
@property (nonatomic) CGFloat cellHeight;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
/// The background color of the selected cell in the drop down.
/// Changing the background color automatically reloads the drop down.
@property (nonatomic, strong) UIColor * _Nonnull selectionBackgroundColor;
/// The separator color between cells.
/// Changing the separator color automatically reloads the drop down.
@property (nonatomic, strong) UIColor * _Nonnull separatorColor;
/// The corner radius of DropDown.
/// Changing the corner radius automatically reloads the drop down.
@property (nonatomic) CGFloat cornerRadius;
/// Alias method for <code>cornerRadius</code> variable to avoid ambiguity.
- (void)setupCornerRadius:(CGFloat)radius;
/// The masked corners of DropDown.
/// Changing the masked corners automatically reloads the drop down.
- (void)setupMaskedCorners:(CACornerMask)cornerMask SWIFT_AVAILABILITY(ios,introduced=11.0);
/// The color of the shadow.
/// Changing the shadow color automatically reloads the drop down.
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
/// The offset of the shadow.
/// Changing the shadow color automatically reloads the drop down.
@property (nonatomic) CGSize shadowOffset;
/// The opacity of the shadow.
/// Changing the shadow opacity automatically reloads the drop down.
@property (nonatomic) float shadowOpacity;
/// The radius of the shadow.
/// Changing the shadow radius automatically reloads the drop down.
@property (nonatomic) CGFloat shadowRadius;
/// The duration of the show/hide animation.
@property (nonatomic) double animationduration;
/// The color of the text for each cells of the drop down.
/// Changing the text color automatically reloads the drop down.
@property (nonatomic, strong) UIColor * _Nonnull textColor;
/// The color of the text for selected cells of the drop down.
/// Changing the text color automatically reloads the drop down.
@property (nonatomic, strong) UIColor * _Nonnull selectedTextColor;
/// The font of the text for each cells of the drop down.
/// Changing the text font automatically reloads the drop down.
@property (nonatomic, strong) UIFont * _Nonnull textFont;
/// Creates a new instance of a drop down.
/// Don’t forget to setup the <code>dataSource</code>,
/// the <code>anchorView</code> and the <code>selectionAction</code>
/// at least before calling <code>show()</code>.
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIEvent;

@interface DropDown (SWIFT_EXTENSION(ShuftiPro))
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end


@interface DropDown (SWIFT_EXTENSION(ShuftiPro))
/// Starts listening to keyboard events.
/// Allows the drop down to display correctly when keyboard is showed.
+ (void)startListeningToKeyboard;
@end


@interface DropDown (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class NSDictionary;

@interface DropDown (SWIFT_EXTENSION(ShuftiPro))
/// An Objective-C alias for the show() method which converts the returned tuple into an NSDictionary.
///
/// returns:
/// An NSDictionary with a value for the “canBeDisplayed” Bool, and possibly for the “offScreenHeight” Optional(CGFloat).
- (NSDictionary * _Nonnull)show SWIFT_WARN_UNUSED_RESULT;
- (BOOL)accessibilityPerformEscape SWIFT_WARN_UNUSED_RESULT;
@end


@interface DropDown (SWIFT_EXTENSION(ShuftiPro))
- (void)updateConstraints;
- (void)layoutSubviews;
@end


@interface DropDown (SWIFT_EXTENSION(ShuftiPro))
- (void)selectRow:(NSInteger)index scrollPosition:(UITableViewScrollPosition)scrollPosition;
- (void)clearSelection;
- (void)deselectRow:(NSInteger)index;
@property (nonatomic, readonly, strong) NSIndexPath * _Nullable indexPathForSelectedRow;
@end


SWIFT_CLASS("_TtC9ShuftiPro12DropDownCell")
@interface DropDownCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified optionLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface DropDownCell (SWIFT_EXTENSION(ShuftiPro))
- (void)awakeFromNib;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end



SWIFT_CLASS("_TtC9ShuftiPro21LanguageTableViewCell")
@interface LanguageTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified languageLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro13LoadingButton")
@interface LoadingButton : UIButton
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9ShuftiPro18NFCDetailTableCell")
@interface NFCDetailTableCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nfcDetailHeading;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nfcDetailSubText;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified sepratorView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro17NFCImageTableCell")
@interface NFCImageTableCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified nfcPhoto;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC9ShuftiPro26OCRDataInputViewController")
@interface OCRDataInputViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified fullNameView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified fullNameUiView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified firstNameView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified lastNameView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified middleNameView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dobView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified issueDateView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified expiryDateView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified idNumberView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified genderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified addressView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified fullNameSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified firstNameSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified lastNameSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified middleNameSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dobSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified issueDateSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified expiryDateSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified idNumberSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified genderSwitchView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified addressSwitchView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified fullNameTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified firstNameTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified lastNameTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified middleNameTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified dobTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified issueDateTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified expiryDateTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified idNumberTxt;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified genderBtn;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified addressTxt;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified genderTxt;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fullNameError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified firstNameError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lastNameError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified middleNameError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified issueDateError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified expiryDateError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dobDateError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified genderError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified idNumberError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified addressError;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fullNameTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified firstNameTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lastNameTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified middleNameTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified issueDateTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified expiryDateTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified dobDateTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified genderTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified idNumberTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified addressTitle;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified dobCalender;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified dobDownArrow;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified expiryCalender;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified expiryDownArrow;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified issueCalender;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified issueDownArrow;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified genderDownArrow;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dobBorderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified issueDataBorderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified expiryDataBorderView;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified nextBtn;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headingLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subHeadingLabel;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)nextBtnPressed:(id _Nonnull)sender;
- (IBAction)genderDropdownBtnPressed:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface OCRDataInputViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextViewDelegate>
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
@end




@interface OCRDataInputViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextFieldDelegate>
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end



@interface OCRDataInputViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)hideKeyboard;
- (void)dobDatePickerDoneButtonTappedWithTextField:(UITextField * _Nonnull)textField;
- (void)issueDatePickerDoneButtonTapped;
- (void)expiryDatePickerDoneButtonTapped;
@end



SWIFT_CLASS("_TtC9ShuftiPro13OCRFieldModel")
@interface OCRFieldModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStackView;

SWIFT_CLASS("_TtC9ShuftiPro22PoweredByShuftiProView")
@interface PoweredByShuftiProView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified poweredByLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified shuftiProLogo;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified leadingForStackView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified mainStackForShuftiLogo;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro28ProofCapturingViewController")
@interface ProofCapturingViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified capturButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraLayeView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pauseRecording;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified recordVideoButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraOverlayView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified flashButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified backButtonTopView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified buttonsStachView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified poweredByView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoTimerTopView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified videoTimerLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backButtonImage;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified instructionsButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified feedBackIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified documentInstructionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified demoAppDocTypesLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified instructionLabelsStackView;
- (void)viewDidLoad;
- (void)appEnterForGround;
- (void)appEnterBackGround;
- (void)timerChangeAutoCapture;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)capturePicture:(id _Nonnull)sender;
- (IBAction)recordButtonClickAction:(id _Nonnull)sender;
- (IBAction)stopRecordingButtonClickAction:(id _Nonnull)sender;
- (IBAction)feedBackButtonClickAction:(id _Nonnull)sender;
- (IBAction)flashButtonclickAction:(id _Nonnull)sender;
- (IBAction)instructionScreenButtonClickAction:(id _Nonnull)sender;
- (IBAction)backButtonClickAction:(id _Nonnull)sender;
- (void)timerChangeVideo;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface ProofCapturingViewController (SWIFT_EXTENSION(ShuftiPro)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

@class AVCaptureFileOutput;

@interface ProofCapturingViewController (SWIFT_EXTENSION(ShuftiPro)) <AVCaptureFileOutputRecordingDelegate>
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didStartRecordingToOutputFileAtURL:(NSURL * _Nonnull)fileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections;
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
@end


@interface ProofCapturingViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)cameraErrorMessageWithCamErrMsg:(NSString * _Nonnull)camErrMsg;
@end

@class UITouch;

@interface ProofCapturingViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)startAnimation;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end



SWIFT_CLASS("_TtC9ShuftiPro26ProofPreviewViewController")
@interface ProofPreviewViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified previewDocumentHeading;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified previewDocumentSubheading;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified previewAssetFramView;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified contineuButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retakeButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imagePreview;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentText;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified imageViewWidth;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified imageViewHeight;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)contineuButtonClickAction:(id _Nonnull)sender;
- (IBAction)retakeButtonClickAction:(id _Nonnull)sender;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC9ShuftiPro32ProofSubmitOptionsViewController")
@interface ProofSubmitOptionsViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified uploadView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified recordView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraProceedView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified uploadProceedView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoProceedView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified takeCameraLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadProofLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified recordVideoLbl;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified cameraImg;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified uploadImg;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified recordImg;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified howToSubmitProof;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified cameraArrowImg;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified uploadArrowImg;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified recordArrowImg;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)takePhotoBtnPressed:(id _Nonnull)sender;
- (IBAction)uploadFromGalleryBtnPressed:(id _Nonnull)sender;
- (IBAction)recordVideoBtnPressed:(id _Nonnull)sender;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC9ShuftiPro21RectangularDashedView")
@interface RectangularDashedView : UIView
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat dashWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull dashColor;
@property (nonatomic) IBInspectable CGFloat dashLength;
@property (nonatomic) IBInspectable CGFloat betweenDashesSpace;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro20ResultViewController")
@interface ResultViewController : UIViewController <NSURLSessionTaskDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loadingView;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loadingIndicatorImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified waitingMessageLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified pleaseWaitLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadPercentageLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified resultTitleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified resultNoteLabel;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified resultWebView;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified termsAndConditionTextView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified showResultView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retryButton;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified proceedButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)updateScreenOnInternetError;
- (IBAction)retryAction:(id _Nonnull)sender;
- (IBAction)proceedAction:(id _Nonnull)sender;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;

@interface ResultViewController (SWIFT_EXTENSION(ShuftiPro)) <NSURLSessionDelegate>
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession * _Nonnull)session;
@end




@interface ResultViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
@end


@class NSURLSessionTask;
@class NSURLSessionDownloadTask;

@interface ResultViewController (SWIFT_EXTENSION(ShuftiPro)) <NSURLSessionDownloadDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
@end


SWIFT_CLASS("_TtC9ShuftiPro24RetryReasonTableViewCell")
@interface RetryReasonTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified reasonLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro26RetryServiceViewController")
@interface RetryServiceViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified retryLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionLabel;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified retryButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelBtn;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified reasonsTableView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified topSpaceParentView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)retryButtonClickAction:(id _Nonnull)sender;
- (IBAction)cancelButtonClickAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface RetryServiceViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC9ShuftiPro26SelectCountryTableViewCell")
@interface SelectCountryTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified countryLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomLineView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified countryFlagLabel;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISearchBar;

SWIFT_CLASS("_TtC9ShuftiPro27SelectCountryViewController")
@interface SelectCountryViewController : UIViewController
@property (nonatomic, weak) IBOutlet UISearchBar * _Null_unspecified searchBar;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified countryTableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified topInstructionLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified topStack;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewBottomSpace;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified headingTopSpace;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified crossButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified crossImage;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified crossImageWidth;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)crossButtonClickAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SelectCountryViewController (SWIFT_EXTENSION(ShuftiPro)) <UISearchBarDelegate>
- (void)searchBar:(UISearchBar * _Nonnull)searchBar textDidChange:(NSString * _Nonnull)searchText;
@end



@interface SelectCountryViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class NSNotification;

@interface SelectCountryViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)topViewClick:(UITapGestureRecognizer * _Nullable)sender;
- (void)handleKeyboardWillHide:(NSNotification * _Nonnull)notification;
- (void)keyboardDidShowWithNotification:(NSNotification * _Nonnull)notification;
@end


SWIFT_CLASS("_TtC9ShuftiPro34SelectLanguageScreenViewController")
@interface SelectLanguageScreenViewController : UIViewController
@property (nonatomic, weak) IBOutlet UISearchBar * _Null_unspecified searchBar;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified languageTableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified topInstructionLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified topStack;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewBottomSpace;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified crossImage;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SelectLanguageScreenViewController (SWIFT_EXTENSION(ShuftiPro)) <UISearchBarDelegate>
- (void)searchBar:(UISearchBar * _Nonnull)searchBar textDidChange:(NSString * _Nonnull)searchText;
@end


@interface SelectLanguageScreenViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface SelectLanguageScreenViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)topViewClick:(UITapGestureRecognizer * _Nullable)sender;
- (void)crossImageClick:(UITapGestureRecognizer * _Nullable)sender;
- (void)handleKeyboardWillHide:(NSNotification * _Nonnull)notification;
- (void)keyboardDidShowWithNotification:(NSNotification * _Nonnull)notification;
@end


SWIFT_CLASS("_TtC9ShuftiPro24ServiceDeclineReasonCell")
@interface ServiceDeclineReasonCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified serviceTopView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified serviceLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified serviceIcon;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cellContainerView;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightConstraintTableview;
- (void)awakeFromNib;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ServiceDeclineReasonCell (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9ShuftiPro9ShuftiPro")
@interface ShuftiPro : NSObject
- (void)shuftiProVerificationWithRequestObject:(NSDictionary<NSString *, id> * _Nonnull)dataObjectObj authKeys:(NSDictionary<NSString *, NSString *> * _Nonnull)authKeys parentVC:(UIViewController * _Nonnull)pvc configs:(NSDictionary<NSString *, id> * _Nullable)configs completion:(void (^ _Nonnull)(id _Nonnull))completion;
- (NSString * _Nonnull)getUniqueReference SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro15ShuftiProRouter")
@interface ShuftiProRouter : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIProgressView;

SWIFT_CLASS("_TtC9ShuftiPro11StepperView")
@interface StepperView : UIView
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified servicesStackView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified serviceLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified helpIcon;
@property (nonatomic, weak) IBOutlet UIProgressView * _Null_unspecified stepperProgressBar;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified servicesLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified backButtonView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (IBAction)backAction:(id _Nonnull)sender;
- (IBAction)infoButtonClickAction:(id _Nonnull)sender;
@end


SWIFT_CLASS("_TtC9ShuftiPro36SupportedDocumentsListViewController")
@interface SupportedDocumentsListViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified selectedCountryFlagLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified selectCountryButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified selectedCountryLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionLabelToChooseDocument;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified supportedTypesLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified countryDownArrow;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified countryView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewHeight;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)selectCountryClickAction:(id _Nonnull)sender;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface SupportedDocumentsListViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC9ShuftiPro32SupportedTypesSceenTableViewCell")
@interface SupportedTypesSceenTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewHeight;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified tableViewTopView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SupportedTypesSceenTableViewCell (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC9ShuftiPro10ToastLabel")
@interface ToastLabel : InsetsLabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro12TriangleView")
@interface TriangleView : UIView
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIBarButtonItem (SWIFT_EXTENSION(ShuftiPro)) <AnchorView>
@property (nonatomic, readonly, strong) UIView * _Nonnull plainView;
@end
















@interface UIView (SWIFT_EXTENSION(ShuftiPro)) <AnchorView>
@property (nonatomic, readonly, strong) UIView * _Nonnull plainView;
@end






SWIFT_CLASS("_TtC9ShuftiPro25UploadProofViewController")
@interface UploadProofViewController : UIViewController
@property (nonatomic, weak) IBOutlet RectangularDashedView * _Null_unspecified uploadProofMainView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified documentstypesLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified browseLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified maximumSizeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentText;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified documentIconImage;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified uploadViewColorHolder;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)browseClickAction:(id _Nonnull)sender;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)presentGeneralAlertInternetIssue;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIDocumentPickerViewController;

@interface UploadProofViewController (SWIFT_EXTENSION(ShuftiPro)) <UIDocumentPickerDelegate>
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController * _Nonnull)controller;
@end

@class UIImagePickerController;

@interface UploadProofViewController (SWIFT_EXTENSION(ShuftiPro)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
@end



SWIFT_CLASS("_TtC9ShuftiPro31UserConsentTakingViewController")
@interface UserConsentTakingViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentHeadingLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentDetail;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelBtn;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified continueBtn;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified policyCheckBoxImg;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified privacyPolicyClickButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified langIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified langNameLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified downArrow;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified languageChangeView;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified termsAndConditionTextView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)privacyPolicyClickAction:(id _Nonnull)sender;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)selectLanguage:(UITapGestureRecognizer * _Nonnull)sender;
- (IBAction)contineuButtonClickAction:(id _Nonnull)sender;
- (IBAction)cancelButtonClickAction:(id _Nonnull)sender;
- (void)callBackWithNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserConsentTakingViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
- (void)textViewDidChangeSelection:(UITextView * _Nonnull)textView;
@end

@class UIGestureRecognizer;

@interface UserConsentTakingViewController (SWIFT_EXTENSION(ShuftiPro))
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC9ShuftiPro26UserFeedBackViewController")
@interface UserFeedBackViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified otherTextView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified helpView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified countingLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified radioIMG1;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified radioIMG2;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified radioIMG3;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified radioIMG4;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headerLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subHeaderLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified optionLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified optionLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified optionLabel3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified optionLabel4;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified submitBtn;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified crossImage;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified scrollview;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightForTextView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserFeedBackViewController (SWIFT_EXTENSION(ShuftiPro)) <UITextViewDelegate>
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end


@interface UserFeedBackViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)keyboardDidShowWithNotification:(NSNotification * _Nonnull)notification;
- (void)keyboardGestures:(UITapGestureRecognizer * _Nonnull)gesture;
- (void)scrollViewClick:(UITapGestureRecognizer * _Nullable)sender;
- (void)helpViewClick:(UITapGestureRecognizer * _Nullable)sender;
- (void)handleKeyboardWillHide:(NSNotification * _Nonnull)notification;
- (IBAction)btn1Pressed:(id _Nonnull)sender;
- (IBAction)btn2Pressed:(id _Nonnull)sender;
- (IBAction)btn3Pressed:(id _Nonnull)sender;
- (IBAction)otherBtnPressed:(id _Nonnull)sender;
- (IBAction)crossButtonClickAction:(id _Nonnull)sender;
- (IBAction)submitBtnPressed:(id _Nonnull)sender;
@end


SWIFT_CLASS("_TtC9ShuftiPro38VerificationRequirementsViewController")
@interface VerificationRequirementsViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified viewHeadingStack;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified headingLable;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subHeadingLable;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified endInstructionLable;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified proceedBtn;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)swipeRightGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (IBAction)proceedButtonClickAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VerificationRequirementsViewController (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface VerificationRequirementsViewController (SWIFT_EXTENSION(ShuftiPro))
- (void)presentGeneralAlertInternetIssue;
@end


SWIFT_CLASS("_TtC9ShuftiPro32VerificationSectionTableViewCell")
@interface VerificationSectionTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified sectionView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified sectionLableImg;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified serviceLable;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified subTitleLable;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified sectionArrowImg;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified arrowTopView;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified typesTableView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightTableView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface VerificationSectionTableViewCell (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9ShuftiPro30VerificationTypesTableViewCell")
@interface VerificationTypesTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified typeLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified arrowButton;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified leadingConstraintforlabel;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified topSpace;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified bottomSpace;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro24WebProcessViewController")
@interface WebProcessViewController : UIViewController
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loadingIndicatorWebView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified heightForNavView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified navBarView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified webHolderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified backViewForProgress;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)callBackWithNotification:(NSNotification * _Nonnull)notification;
- (IBAction)cancelButtonAction:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@class WKNavigation;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;

@interface WebProcessViewController (SWIFT_EXTENSION(ShuftiPro)) <WKNavigationDelegate, WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)_ decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)decidePolicyFor decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
